//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.1433 版自动生成。
// 
#pragma warning disable 1591

namespace Ucar.Components.UcarService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreateHtmlSoap", Namespace="http://tempuri.org/")]
    public partial class CreateHtml : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateRecommandHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDayHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateWeekHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAppraiserListHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBlogListHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHotPostListHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHotBlogHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBespokeRecommandListHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewsListHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHtml_UpOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHtmlNew_UpOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHtmlNew_DownOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHtml_DownOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateQDetailHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHotQuestionListHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateIndexQuestionHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSinaIndexQuestionHtmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateTranstarCarSourceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCarInfoTemplateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreateHtml() {
            this.Url = global::Ucar.Components.Properties.Settings.Default.Ucar_Components_UcarService_CreateHtml;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateRecommandHtmlCompletedEventHandler CreateRecommandHtmlCompleted;
        
        /// <remarks/>
        public event CreateDayHtmlCompletedEventHandler CreateDayHtmlCompleted;
        
        /// <remarks/>
        public event CreateWeekHtmlCompletedEventHandler CreateWeekHtmlCompleted;
        
        /// <remarks/>
        public event CreateAppraiserListHtmlCompletedEventHandler CreateAppraiserListHtmlCompleted;
        
        /// <remarks/>
        public event CreateBlogListHtmlCompletedEventHandler CreateBlogListHtmlCompleted;
        
        /// <remarks/>
        public event CreateHotPostListHtmlCompletedEventHandler CreateHotPostListHtmlCompleted;
        
        /// <remarks/>
        public event CreateHotBlogHtmlCompletedEventHandler CreateHotBlogHtmlCompleted;
        
        /// <remarks/>
        public event CreateBespokeRecommandListHtmlCompletedEventHandler CreateBespokeRecommandListHtmlCompleted;
        
        /// <remarks/>
        public event CreateNewsListHtmlCompletedEventHandler CreateNewsListHtmlCompleted;
        
        /// <remarks/>
        public event CreateHtml_UpCompletedEventHandler CreateHtml_UpCompleted;
        
        /// <remarks/>
        public event CreateHtmlNew_UpCompletedEventHandler CreateHtmlNew_UpCompleted;
        
        /// <remarks/>
        public event CreateHtmlNew_DownCompletedEventHandler CreateHtmlNew_DownCompleted;
        
        /// <remarks/>
        public event CreateHtml_DownCompletedEventHandler CreateHtml_DownCompleted;
        
        /// <remarks/>
        public event CreateQDetailHtmlCompletedEventHandler CreateQDetailHtmlCompleted;
        
        /// <remarks/>
        public event CreateHotQuestionListHtmlCompletedEventHandler CreateHotQuestionListHtmlCompleted;
        
        /// <remarks/>
        public event CreateIndexQuestionHtmlCompletedEventHandler CreateIndexQuestionHtmlCompleted;
        
        /// <remarks/>
        public event CreateSinaIndexQuestionHtmlCompletedEventHandler CreateSinaIndexQuestionHtmlCompleted;
        
        /// <remarks/>
        public event CreateTranstarCarSourceListCompletedEventHandler CreateTranstarCarSourceListCompleted;
        
        /// <remarks/>
        public event CreateCarInfoTemplateCompletedEventHandler CreateCarInfoTemplateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateRecommandHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateRecommandHtml() {
            this.Invoke("CreateRecommandHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateRecommandHtmlAsync() {
            this.CreateRecommandHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateRecommandHtmlAsync(object userState) {
            if ((this.CreateRecommandHtmlOperationCompleted == null)) {
                this.CreateRecommandHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRecommandHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateRecommandHtml", new object[0], this.CreateRecommandHtmlOperationCompleted, userState);
        }
        
        private void OnCreateRecommandHtmlOperationCompleted(object arg) {
            if ((this.CreateRecommandHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRecommandHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateDayHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDayHtml() {
            this.Invoke("CreateDayHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateDayHtmlAsync() {
            this.CreateDayHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateDayHtmlAsync(object userState) {
            if ((this.CreateDayHtmlOperationCompleted == null)) {
                this.CreateDayHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDayHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateDayHtml", new object[0], this.CreateDayHtmlOperationCompleted, userState);
        }
        
        private void OnCreateDayHtmlOperationCompleted(object arg) {
            if ((this.CreateDayHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDayHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateWeekHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateWeekHtml() {
            this.Invoke("CreateWeekHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateWeekHtmlAsync() {
            this.CreateWeekHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateWeekHtmlAsync(object userState) {
            if ((this.CreateWeekHtmlOperationCompleted == null)) {
                this.CreateWeekHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWeekHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateWeekHtml", new object[0], this.CreateWeekHtmlOperationCompleted, userState);
        }
        
        private void OnCreateWeekHtmlOperationCompleted(object arg) {
            if ((this.CreateWeekHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWeekHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateAppraiserListHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateAppraiserListHtml() {
            this.Invoke("CreateAppraiserListHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateAppraiserListHtmlAsync() {
            this.CreateAppraiserListHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateAppraiserListHtmlAsync(object userState) {
            if ((this.CreateAppraiserListHtmlOperationCompleted == null)) {
                this.CreateAppraiserListHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAppraiserListHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateAppraiserListHtml", new object[0], this.CreateAppraiserListHtmlOperationCompleted, userState);
        }
        
        private void OnCreateAppraiserListHtmlOperationCompleted(object arg) {
            if ((this.CreateAppraiserListHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAppraiserListHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateBlogListHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateBlogListHtml() {
            this.Invoke("CreateBlogListHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateBlogListHtmlAsync() {
            this.CreateBlogListHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateBlogListHtmlAsync(object userState) {
            if ((this.CreateBlogListHtmlOperationCompleted == null)) {
                this.CreateBlogListHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBlogListHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateBlogListHtml", new object[0], this.CreateBlogListHtmlOperationCompleted, userState);
        }
        
        private void OnCreateBlogListHtmlOperationCompleted(object arg) {
            if ((this.CreateBlogListHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBlogListHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHotPostListHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHotPostListHtml() {
            this.Invoke("CreateHotPostListHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHotPostListHtmlAsync() {
            this.CreateHotPostListHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateHotPostListHtmlAsync(object userState) {
            if ((this.CreateHotPostListHtmlOperationCompleted == null)) {
                this.CreateHotPostListHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHotPostListHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateHotPostListHtml", new object[0], this.CreateHotPostListHtmlOperationCompleted, userState);
        }
        
        private void OnCreateHotPostListHtmlOperationCompleted(object arg) {
            if ((this.CreateHotPostListHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHotPostListHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHotBlogHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHotBlogHtml() {
            this.Invoke("CreateHotBlogHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHotBlogHtmlAsync() {
            this.CreateHotBlogHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateHotBlogHtmlAsync(object userState) {
            if ((this.CreateHotBlogHtmlOperationCompleted == null)) {
                this.CreateHotBlogHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHotBlogHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateHotBlogHtml", new object[0], this.CreateHotBlogHtmlOperationCompleted, userState);
        }
        
        private void OnCreateHotBlogHtmlOperationCompleted(object arg) {
            if ((this.CreateHotBlogHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHotBlogHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateBespokeRecommandListHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateBespokeRecommandListHtml() {
            this.Invoke("CreateBespokeRecommandListHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateBespokeRecommandListHtmlAsync() {
            this.CreateBespokeRecommandListHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateBespokeRecommandListHtmlAsync(object userState) {
            if ((this.CreateBespokeRecommandListHtmlOperationCompleted == null)) {
                this.CreateBespokeRecommandListHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBespokeRecommandListHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateBespokeRecommandListHtml", new object[0], this.CreateBespokeRecommandListHtmlOperationCompleted, userState);
        }
        
        private void OnCreateBespokeRecommandListHtmlOperationCompleted(object arg) {
            if ((this.CreateBespokeRecommandListHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBespokeRecommandListHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateNewsListHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateNewsListHtml() {
            this.Invoke("CreateNewsListHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateNewsListHtmlAsync() {
            this.CreateNewsListHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateNewsListHtmlAsync(object userState) {
            if ((this.CreateNewsListHtmlOperationCompleted == null)) {
                this.CreateNewsListHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewsListHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateNewsListHtml", new object[0], this.CreateNewsListHtmlOperationCompleted, userState);
        }
        
        private void OnCreateNewsListHtmlOperationCompleted(object arg) {
            if ((this.CreateNewsListHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewsListHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHtml_Up", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHtml_Up() {
            this.Invoke("CreateHtml_Up", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHtml_UpAsync() {
            this.CreateHtml_UpAsync(null);
        }
        
        /// <remarks/>
        public void CreateHtml_UpAsync(object userState) {
            if ((this.CreateHtml_UpOperationCompleted == null)) {
                this.CreateHtml_UpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHtml_UpOperationCompleted);
            }
            this.InvokeAsync("CreateHtml_Up", new object[0], this.CreateHtml_UpOperationCompleted, userState);
        }
        
        private void OnCreateHtml_UpOperationCompleted(object arg) {
            if ((this.CreateHtml_UpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHtml_UpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHtmlNew_Up", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHtmlNew_Up() {
            this.Invoke("CreateHtmlNew_Up", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHtmlNew_UpAsync() {
            this.CreateHtmlNew_UpAsync(null);
        }
        
        /// <remarks/>
        public void CreateHtmlNew_UpAsync(object userState) {
            if ((this.CreateHtmlNew_UpOperationCompleted == null)) {
                this.CreateHtmlNew_UpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHtmlNew_UpOperationCompleted);
            }
            this.InvokeAsync("CreateHtmlNew_Up", new object[0], this.CreateHtmlNew_UpOperationCompleted, userState);
        }
        
        private void OnCreateHtmlNew_UpOperationCompleted(object arg) {
            if ((this.CreateHtmlNew_UpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHtmlNew_UpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHtmlNew_Down", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHtmlNew_Down() {
            this.Invoke("CreateHtmlNew_Down", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHtmlNew_DownAsync() {
            this.CreateHtmlNew_DownAsync(null);
        }
        
        /// <remarks/>
        public void CreateHtmlNew_DownAsync(object userState) {
            if ((this.CreateHtmlNew_DownOperationCompleted == null)) {
                this.CreateHtmlNew_DownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHtmlNew_DownOperationCompleted);
            }
            this.InvokeAsync("CreateHtmlNew_Down", new object[0], this.CreateHtmlNew_DownOperationCompleted, userState);
        }
        
        private void OnCreateHtmlNew_DownOperationCompleted(object arg) {
            if ((this.CreateHtmlNew_DownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHtmlNew_DownCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHtml_Down", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHtml_Down() {
            this.Invoke("CreateHtml_Down", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHtml_DownAsync() {
            this.CreateHtml_DownAsync(null);
        }
        
        /// <remarks/>
        public void CreateHtml_DownAsync(object userState) {
            if ((this.CreateHtml_DownOperationCompleted == null)) {
                this.CreateHtml_DownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHtml_DownOperationCompleted);
            }
            this.InvokeAsync("CreateHtml_Down", new object[0], this.CreateHtml_DownOperationCompleted, userState);
        }
        
        private void OnCreateHtml_DownOperationCompleted(object arg) {
            if ((this.CreateHtml_DownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHtml_DownCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateQDetailHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateQDetailHtml(int moc_Id) {
            this.Invoke("CreateQDetailHtml", new object[] {
                        moc_Id});
        }
        
        /// <remarks/>
        public void CreateQDetailHtmlAsync(int moc_Id) {
            this.CreateQDetailHtmlAsync(moc_Id, null);
        }
        
        /// <remarks/>
        public void CreateQDetailHtmlAsync(int moc_Id, object userState) {
            if ((this.CreateQDetailHtmlOperationCompleted == null)) {
                this.CreateQDetailHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateQDetailHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateQDetailHtml", new object[] {
                        moc_Id}, this.CreateQDetailHtmlOperationCompleted, userState);
        }
        
        private void OnCreateQDetailHtmlOperationCompleted(object arg) {
            if ((this.CreateQDetailHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateQDetailHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateHotQuestionListHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHotQuestionListHtml() {
            this.Invoke("CreateHotQuestionListHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateHotQuestionListHtmlAsync() {
            this.CreateHotQuestionListHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateHotQuestionListHtmlAsync(object userState) {
            if ((this.CreateHotQuestionListHtmlOperationCompleted == null)) {
                this.CreateHotQuestionListHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHotQuestionListHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateHotQuestionListHtml", new object[0], this.CreateHotQuestionListHtmlOperationCompleted, userState);
        }
        
        private void OnCreateHotQuestionListHtmlOperationCompleted(object arg) {
            if ((this.CreateHotQuestionListHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHotQuestionListHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateIndexQuestionHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateIndexQuestionHtml() {
            this.Invoke("CreateIndexQuestionHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateIndexQuestionHtmlAsync() {
            this.CreateIndexQuestionHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateIndexQuestionHtmlAsync(object userState) {
            if ((this.CreateIndexQuestionHtmlOperationCompleted == null)) {
                this.CreateIndexQuestionHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateIndexQuestionHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateIndexQuestionHtml", new object[0], this.CreateIndexQuestionHtmlOperationCompleted, userState);
        }
        
        private void OnCreateIndexQuestionHtmlOperationCompleted(object arg) {
            if ((this.CreateIndexQuestionHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateIndexQuestionHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateSinaIndexQuestionHtml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateSinaIndexQuestionHtml() {
            this.Invoke("CreateSinaIndexQuestionHtml", new object[0]);
        }
        
        /// <remarks/>
        public void CreateSinaIndexQuestionHtmlAsync() {
            this.CreateSinaIndexQuestionHtmlAsync(null);
        }
        
        /// <remarks/>
        public void CreateSinaIndexQuestionHtmlAsync(object userState) {
            if ((this.CreateSinaIndexQuestionHtmlOperationCompleted == null)) {
                this.CreateSinaIndexQuestionHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSinaIndexQuestionHtmlOperationCompleted);
            }
            this.InvokeAsync("CreateSinaIndexQuestionHtml", new object[0], this.CreateSinaIndexQuestionHtmlOperationCompleted, userState);
        }
        
        private void OnCreateSinaIndexQuestionHtmlOperationCompleted(object arg) {
            if ((this.CreateSinaIndexQuestionHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSinaIndexQuestionHtmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateTranstarCarSourceList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateTranstarCarSourceList(int PublishRange, int VendorUcarID) {
            this.Invoke("CreateTranstarCarSourceList", new object[] {
                        PublishRange,
                        VendorUcarID});
        }
        
        /// <remarks/>
        public void CreateTranstarCarSourceListAsync(int PublishRange, int VendorUcarID) {
            this.CreateTranstarCarSourceListAsync(PublishRange, VendorUcarID, null);
        }
        
        /// <remarks/>
        public void CreateTranstarCarSourceListAsync(int PublishRange, int VendorUcarID, object userState) {
            if ((this.CreateTranstarCarSourceListOperationCompleted == null)) {
                this.CreateTranstarCarSourceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateTranstarCarSourceListOperationCompleted);
            }
            this.InvokeAsync("CreateTranstarCarSourceList", new object[] {
                        PublishRange,
                        VendorUcarID}, this.CreateTranstarCarSourceListOperationCompleted, userState);
        }
        
        private void OnCreateTranstarCarSourceListOperationCompleted(object arg) {
            if ((this.CreateTranstarCarSourceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateTranstarCarSourceListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCarInfoTemplate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateCarInfoTemplate(int UcarID) {
            this.Invoke("CreateCarInfoTemplate", new object[] {
                        UcarID});
        }
        
        /// <remarks/>
        public void CreateCarInfoTemplateAsync(int UcarID) {
            this.CreateCarInfoTemplateAsync(UcarID, null);
        }
        
        /// <remarks/>
        public void CreateCarInfoTemplateAsync(int UcarID, object userState) {
            if ((this.CreateCarInfoTemplateOperationCompleted == null)) {
                this.CreateCarInfoTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCarInfoTemplateOperationCompleted);
            }
            this.InvokeAsync("CreateCarInfoTemplate", new object[] {
                        UcarID}, this.CreateCarInfoTemplateOperationCompleted, userState);
        }
        
        private void OnCreateCarInfoTemplateOperationCompleted(object arg) {
            if ((this.CreateCarInfoTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCarInfoTemplateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateRecommandHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateDayHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateWeekHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateAppraiserListHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateBlogListHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHotPostListHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHotBlogHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateBespokeRecommandListHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateNewsListHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHtml_UpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHtmlNew_UpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHtmlNew_DownCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHtml_DownCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateQDetailHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateHotQuestionListHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateIndexQuestionHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateSinaIndexQuestionHtmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateTranstarCarSourceListCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateCarInfoTemplateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591